sudo pacman -S --noconfirm fzf
sudo pacman -S --noconfirm ripgrep
sudo pacman -S --noconfirm bat
sudo pacman -S --noconfirm eza
sudo pacman -S --noconfirm zoxide
sudo pacman -S --noconfirm plocate
sudo pacman -S --noconfirm btop
sudo pacman -S --noconfirm fd
sudo pacman -S --noconfirm tldr
sudo pacman -S --noconfirm fastfetch
sudo pacman -S --noconfirm wireguard-tools
sudo pacman -S --noconfirm go-yq
sudo pacman -S --noconfirm jq
sudo pacman -S --noconfirm yt-dlp
sudo pacman -S --noconfirm gnome-disk-utilit
